// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlite

import (
	"database/sql"
)

type Group struct {
	ID          int64
	GroupName   string
	Description sql.NullString
	UuidList    string
	DateAdded   sql.NullTime
	DateUpdated sql.NullTime
}

type Snippet struct {
	ID           int64
	Uuid         string
	Name         sql.NullString
	Code         string
	Language     string
	Tags         sql.NullString
	Description  sql.NullString
	Source       sql.NullString
	DateAdded    sql.NullTime
	Version      int64
	SupersededBy sql.NullInt64
}
